Conserve id when next to data key, resolves #700
facebookarchive/php-graph-sdk pull request #1034
Opened 2018-07-25 15:25 UTC by foaly-nr1

#700 is still consistently a problem across all versions of the Graph API.

2018-11-14 06:48 UTC, yguedidi commented
@foaly-nr1 thanks for the PR! I'm closing it as #817 was opened before and that it's a more generic solution.
Your solution may lead to issue in case there is another `id` key under `data` key, so I prefer solution in #817

2018-11-14 13:02 UTC, foaly-nr1 commented
@yguedidi the documentation for `array_merge()` states:

> If the input arrays have the same string keys, then the later value for that key will overwrite the previous one.

So there wouldn't be an issue in case there is another `id` key under `data`.

2018-11-15 07:33 UTC, yguedidi commented
@foaly-nr1 Yes I know, that's why it's an issue. Overwriting the `id` that is outside the `data` key is a loss of data. I answered in https://github.com/facebook/php-graph-sdk/pull/817#issuecomment-438944185 what should be the behavior IMO

2018-11-22 20:47 UTC, yguedidi commented
@foaly-nr1 here updated expected behavior
- if only a `data` key and no other keys (like `picture` in @tolbon above example): use the data for the node (`$data = $data['data']`)
- otherwise, use `data` key plus any other sibling key to `data`

So, something like:
```php
$outerData = $data;
unset($outerData['data']);
$data = $data['data'] + $outerData;
```
This keeps BC, and make most of key that were not accessible at all previous now accessible.
This doesn't solve the case where there is the same key next to `data` and inside `data`, but at least it's an improvement and should solve most issues.

Can you update you PR and target 5.x please? so this fix is part of the 5.7.0 release? Thanks

2018-11-22 20:53 UTC, yguedidi requested changes
Please rebase on `5.x` branch, target it in the PR and update the changelog too (use PR number in the changelog)

2018-11-22 20:53 UTC, yguedidi commented on tests/GraphNode/GraphNodeFactoryTest.php
> +            'id' => '123',
please add another key next do `id` and `data` here

2018-11-22 20:53 UTC, yguedidi commented on tests/GraphNode/GraphNodeFactoryTest.php
> +        $this->assertInstanceOf(GraphNode::class, $graphNode);
please don't use `::class`, SDK v5 supports PHP 5.4

2018-11-22 20:53 UTC, yguedidi commented on tests/GraphNode/GraphNodeFactoryTest.php
> +    public function testAGraphNodeWithARootDataKeyWillConserveId()
should be renamed then to `...ConserveRootKeys()`

2018-11-22 20:59 UTC, yguedidi commented on src/GraphNode/GraphNodeFactory.php
> +            $data = array_merge((isset($data['id']) ? ['id' => $data['id']] : []), $data['data']);
```suggestion
            $outerData = $data;
            unset($outerData['data']);
            $data = $data['data'] + $outerData;
```

2018-11-22 21:01 UTC, yguedidi commented on tests/GraphNode/GraphNodeFactoryTest.php
> +            'id' => '123',
```suggestion
            'id' => '123',
            'foo' => 'bar',
```

2018-11-23 00:08 UTC, foaly-nr1 commented
All done and change log updated.

2018-11-23 07:43 UTC, yguedidi approved these changes

2018-11-23 07:44 UTC, merged

2018-11-23 16:17 UTC, foaly-nr1 commented
It's been merged!!  🎉 Fittingly it was the 2 year anniversary of my bug report of this issue last week.