Fix #1076
facebookarchive/php-graph-sdk pull request #1079
Opened 2018-11-08 19:41 UTC by bytestream

2018-11-12 22:23 UTC, yguedidi commented
@bytestream thanks for this contribution! It looks like the branch is not up to date and that ou have to sign the CLA. Do you plan to do so? @jestinas also opened a fix for the bug, but you opened it first so either you update your PR and I accept yours, or let @jestinas update his PR. :)

2018-11-12 22:59 UTC, bytestream commented
@yguedidi signed and updated.

If you could tag a 5.6 release that would be great.

2018-11-13 07:17 UTC, yguedidi commented
Thanks @bytestream! Can you please also update the changelog and add a test for this case so it doesn't break later? thanks again

2018-11-14 06:54 UTC, yguedidi requested changes
final changes! please also squash your PR in one commit, then I'll merge it, thanks!

2018-11-14 06:54 UTC, yguedidi commented on CHANGELOG.md
> +  - Fixed HTTP/2 support (#1076)
we usually link the PR instead of the issue

2018-11-14 06:54 UTC, yguedidi commented on tests/Http/GraphRawResponseTest.php
> +        $headers = str_replace("HTTP/1.1", "HTTP/1.0", $this->fakeRawHeader);
we use single quotes we possible. Same below

2018-11-14 15:50 UTC, bytestream commented
Squashed 👍

2018-11-15 07:40 UTC, yguedidi approved these changes

2018-11-15 07:40 UTC, merged

2018-11-15 07:41 UTC, yguedidi commented
Thanks @bytestream! will be release soon, once the 5.7.0 milestone is completed!

2018-12-10 07:48 UTC, julienbourdeau commented
Any ETA for the 5.7 release? The [milestone](https://github.com/facebook/php-graph-sdk/milestone/11) seems complete.

2018-12-12 18:54 UTC, julienbourdeau commented
Until this is release, I had to use my fork to use the current branch, I'll get rid of this when 5.7 is out.

If you're interested:

1. fork repository
2. update `composer.json`
```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/julienbourdeau/php-graph-sdk"
        }
    ],
    "require": {
        "php": "^7.1.3",
        "facebook/graph-sdk": "5.x-dev"
    },
```
3. delete vendor folder (just in case) `rm -rf vendor/facebook`
4. Update with `composer update`

2018-12-15 18:49 UTC, yguedidi commented
@julienbourdeau 5.7.0 finally released! Sorry for the delay!

2018-12-17 09:37 UTC, julienbourdeau commented
@yguedidi Great! Thanks, I didn't expect it before christmas. 💯