Fix for HTTP v2
facebookarchive/php-graph-sdk pull request #1081
Opened 2018-11-12 12:41 UTC by jestinas

2018-11-12 22:17 UTC, yguedidi requested changes
Please also add a test and update the changelog, thanks.

2018-11-12 22:17 UTC, yguedidi commented on src/Facebook/Http/GraphRawResponse.php
> +        $this->httpResponseCode = (int)$match[1];*/
comment must be removed

2018-11-12 22:17 UTC, yguedidi commented
@jestinas thank you for your contribution! I did the review :)

2018-11-13 07:18 UTC, yguedidi commented
Sorry @jestinas, I'm closing this in favor of #1079 as it was open before. Can't wait to see you contribute again!

2018-11-13 07:18 UTC, closed without merging

2018-11-13 09:01 UTC, jestinas commented
@yguedidi Cool brother. :)